log syslog all;

router id 10.10.10.40;

protocol kernel {
  ipv4 {
    import all;
    export all;
  };
  persist;
  learn;
  scan time 20;
}

protocol device {
  scan time 10;
}

protocol direct {
  ipv4;
  interface "eth2";
}

template bgp k8s_node {
  local 10.10.10.40 as 65001;
  ipv4 {
    import filter {
      gw = from;
      accept;
    };
    export none;
  };
}

protocol bgp k8s_node_1 from k8s_node {
  neighbor 10.10.10.11 as 65001;
}

protocol bgp k8s_node_2 from k8s_node {
  neighbor 10.10.10.12 as 65001;
}

protocol bgp k8s_node_3 from k8s_node {
  neighbor 10.10.10.13 as 65001;
}

protocol bgp k8s_worker_1 from k8s_node {
  neighbor 10.10.10.21 as 65001;
}

protocol bgp k8s_worker_2 from k8s_node {
  neighbor 10.10.10.22 as 65001;
}
