---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    bgp: public
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
  externalTrafficPolicy: Local
